import '@tensorflow/tfjs-node';
import { load, UniversalSentenceEncoder } from '@tensorflow-models/universal-sentence-encoder';

let model: UniversalSentenceEncoder;

export async function loadModel() {
  if (!model) {
    model = await load();
  }

  return model;
}

/**
 * Retrieves the embedding for a given text using a provided model.
 *
 * @param model - The model used to generate the embedding.
 * @param text - The text for which the embedding is generated.
 * @return The embedding array generated by the model.
 */
export async function getEmbedding(model: UniversalSentenceEncoder, text: string) {
  const embeddings = await model.embed([text]);
  const embeddingArray = embeddings.arraySync();

  return embeddingArray[0];
}
